import Link from 'next/link';
import { Header } from '@/components/header';
import { Footer } from '@/components/footer';
import { pageMetadata, site } from '@/lib/site';

export const metadata = pageMetadata({ title: 'Privacy Notice', description: 'How Pixaloom handles website enquiries, technical logs and contact information, and how to ask a privacy question.', path: '/privacy' });

export default function PrivacyPage() {
  return <><Header /><main id="main-content"><section className="article-hero"><div className="article-container"><p className="eyebrow">Pixaloom · Updated 3 September 2026</p><h1>Privacy notice.</h1><p>This notice covers enquiries and use of the Pixaloom studio website. It does not describe the separate websites or applications shown in our portfolio.</p></div></section><section className="content-section"><div className="article-container article-body">
    <h2>Who to contact</h2><p>Pixaloom is based in {site.location}. For questions about your information, contact Cameron Falck at <a href={`mailto:${site.email}`}>{site.email}</a> or <a href={`tel:${site.phoneInternational}`}>{site.phoneDisplay}</a>.</p>
    <h2>Information you choose to send</h2><p>The enquiry form asks for your name, email and message. Phone, company, service and budget are optional. We use this information to respond, understand the requested work and manage the resulting conversation. Please do not submit passwords, identity documents, payment-card details or sensitive records.</p>
    <h2>Delivery and service providers</h2><p>The website is hosted on Hostinger. When the enquiry form is available, it uses Resend to deliver the message to our business inbox. Hosting and email providers process information needed to operate their services, potentially outside South Africa. Emailing, calling or following a WhatsApp link uses those separate communication providers and their applicable terms. Portfolio links lead to independently operated sites.</p>
    <h2>Technical information and action counts</h2><p>Hosting and communication services may retain technical logs, including network information, for operation and security. Our application records a limited set of action names such as an email-link click, form attempt or delivery failure. These action events contain no form contents, visitor identifier, query string or advertising cookie. A click count is not a confirmed enquiry or sale.</p><p>This website does not currently load advertising trackers or a third-party behavioural analytics script. The cost estimator keeps selections in the current page and can pass the selected project options in the contact URL; it does not place your contact details in that URL.</p>
    <h2>Access, retention and your requests</h2><p>Enquiries are intended for the people handling your request, not for publication. We do not add enquiry senders to a marketing list through this form. Information may remain in the email conversation and relevant business records while it is needed to handle the enquiry, deliver agreed work or meet applicable obligations. Ask us about retention for your particular information.</p><p>You can ask what personal information we hold, request correction or deletion, or raise an objection or concern using the contact above. We may need to verify a request and explain any applicable reason why a record must be retained. You can also contact South Africa's <a href="https://inforegulator.org.za/">Information Regulator</a>.</p>
    <h2>Changes</h2><p>We update this notice when website processing changes. A new analytics provider or marketing use requires a review of the notice and any applicable permissions before activation.</p><p><Link href="/contact">Return to contact</Link></p>
  </div></section></main><Footer /></>;
}
