export const rescuePackages = [
  { name: 'Quick Fix', price: 'R1,490', scope: 'One clearly defined problem.', detail: 'Diagnosis of the agreed issue, implementation, focused testing and a short handover with a Git commit or equivalent change record where supported.' },
  { name: 'Ship It', price: 'R3,990', scope: 'An existing app, ready for its agreed launch.', detail: 'One deployment environment, environment configuration, one domain connection and up to two agreed launch blockers. We test one core journey and hand over a working URL when the reviewed project is suitable.' },
  { name: 'Full Rescue', price: 'From R8,900', scope: 'Several connected problems, one written scope.', detail: 'Assessment first, then a quote for up to four agreed connected issues in one app, one deployment and two core journeys. Larger repairs, unfinished features and rebuilds are quoted separately.' },
] as const;
export const rescueFaqs = [
  ['Can you finish my Lovable or Bolt app?', 'Often, yes. We first check the code access, hosting setup and actual work remaining. Projects started with Lovable, Bolt.new, Replit, Cursor, Claude Code, Codex and v0 can be a fit when the necessary access is available. Closed platforms need a feasibility review before we promise changes.'],
  ['Can you fix a website built with AI?', 'Yes, we can assess an existing AI-built website or web app and fix the agreed issues. You do not need to know the technical cause. Tell us what is broken and what you expected to happen.'],
  ['Why does my app work in preview but fail when deployed?', 'Preview and production may use different environment settings, URLs, database permissions or build steps. We reproduce the failure and check those differences before deciding on a fix.'],
  ['Do I need to give you access to my code?', 'Usually, for implementation. A public repository is not required. We arrange appropriate private invitations later. Do not send passwords, API keys, database credentials or customer records through the enquiry form.'],
  ['Can you help with Supabase login or payment problems?', 'We can assess login, password reset, database permissions, checkout and webhook issues. Payment work uses your supported provider and depends on your business and merchant eligibility. Provider approval is outside our control.'],
  ['Will you need to rebuild everything?', 'Not automatically. We aim to preserve useful work, but a finished-looking interface can hide substantial gaps. If a rebuild is the responsible option, we explain why and quote it separately.'],
  ['What does the free diagnosis include?', 'A brief initial review of the reported issue to understand the problem and recommend a next step. It is not a comprehensive code audit or a commitment to fix the project for free. Deeper diagnosis is part of the agreed paid work.'],
  ['How much does it cost?', 'Quick Fix starts at R1,490, Ship It at R3,990 and Full Rescue at R8,900. We confirm suitability, scope and a delivery estimate after reviewing the issue and required access. Hosting, domains, third-party subscriptions and usage charges are separate.'],
  ['What if the problem is bigger than one package?', 'We share the findings and options before additional work. New features, unrelated bugs and larger rebuilds require a separately agreed scope and price. You are not committing to an open-ended repair.'],
  ['What counts as a revision?', 'A correction to meet the written acceptance criteria for the agreed deliverables. Quick Fix and Ship It include one revision; Full Rescue includes two. New requirements are additional work.'],
  ['Can you maintain the app after launch?', 'Yes, where the project is suitable. App Care is R1,490/month for 1.5 hours; App Care Pro is R2,990/month for 3 hours. The allowance, response windows and exclusions below apply. Maintenance begins only after a written agreement.'],
] as const;
