// Planning examples, not assertions that we have delivered these sectors locally.
export const regionalBriefs: Record<string, { title: string; brief: string; decisions: string[]; guide: string }> = {
  'western-cape': { title: 'One base, different customer journeys.', brief: 'From our George base, we can plan local service sites alongside remote retail and business projects. A guesthouse, specialist shop and professional practice should not receive the same enquiry journey simply because they share a province.', decisions: ['For accommodation: define availability ownership and booking handover.', 'For retail: prepare representative products, delivery areas and payment requirements.', 'For services: explain travel coverage and what a customer needs before requesting a quote.'], guide: 'george-tourism-website-best-practices' },
  gauteng: { title: 'Prepare a brief for a complex buying decision.', brief: 'For a B2B or industrial website, the useful question is often how a buyer qualifies a supplier. We can structure technical information, approved project examples and quote requirements around that process. This is a suggested brief, not a claim of a Gauteng office.', decisions: ['Identify the procurement and end-user audiences separately.', 'Prepare specifications and permitted reference work.', 'Define which quote fields route an enquiry to the right person.'], guide: 'lead-generation-website-design' },
  'kwazulu-natal': { title: 'Separate visitor enquiries from operational enquiries.', brief: 'A tourism booking and a freight-service quote ask for different information. Before design, choose the primary customer journey and decide which operational details belong on the public website and which require a private conversation.', decisions: ['Clarify booking confirmation versus a request for dates.', 'Define service coverage and specialist handling requirements.', 'Assign an owner to availability, opening hours and contact follow-up.'], guide: 'lead-generation-website-design' },
  'eastern-cape': { title: 'Make specialist information easy to act on.', brief: 'For a practice, training provider or manufacturer, clarity may matter more than a large page count. We can help separate service explanations, technical material and enquiry routes. Sensitive information should not be requested through a general contact form.', decisions: ['List the questions a new customer asks before making contact.', 'Identify documents that need an accessible web-page equivalent.', 'Separate public enquiry forms from any protected operational workflow.'], guide: 'web-app-vs-website-difference' },
  'free-state': { title: 'Plan for enquiries from a wide service area.', brief: 'An agricultural or professional-service business can use its website to clarify where work is available and what needs assessment before quoting. Start with actual coverage and customer questions rather than creating repetitive town pages.', decisions: ['Define travel, collection or delivery boundaries.', 'Explain which jobs can be quoted remotely and which need inspection.', 'Prepare authentic examples and the people responsible for the service.'], guide: 'choosing-web-developer-george' },
  limpopo: { title: 'Explain the offer before expanding the page count.', brief: 'For a lodge, supplier or specialist service, useful pages explain suitability and operating requirements. We work remotely from George; the discovery conversation establishes the actual audience rather than assuming every business in Limpopo needs the same layout.', decisions: ['For accommodation: confirm location, access and booking rules.', 'For supply: document product specifications and lead-time ownership.', 'For services: make coverage and contact responsibility explicit.'], guide: 'content-marketing-small-business' },
  mpumalanga: { title: 'Separate tourism discovery from supplier qualification.', brief: 'A visitor comparing an activity and a business comparing a technical supplier need different evidence. We can organise the site around the appropriate decision, with mobile-readable content and a clear next action.', decisions: ['Identify the information needed before a booking or quotation.', 'Check ownership and update frequency of rates or product data.', 'Define whether an existing booking or stock system can be integrated.'], guide: 'web-app-vs-website-difference' },
  'north-west': { title: 'Make capabilities and service limits clear.', brief: 'For supplier and specialist-service briefs, begin with capabilities, verified examples and the information needed to assess a job. For tourism, begin with suitability and availability. These are planning examples, not claims of completed local engagements.', decisions: ['Publish only qualifications and experience you can substantiate.', 'Agree who approves technical specifications and service coverage.', 'Route suitable enquiries without requesting unnecessary confidential data.'], guide: 'lead-generation-website-design' },
  'northern-cape': { title: 'Help customers plan before they travel or order.', brief: 'A website can reduce uncertainty by explaining access, collection, delivery or appointment requirements before someone makes a long trip. The scope depends on the business: a remote service enquiry and an accommodation booking need different details.', decisions: ['Verify directions and physical-access information with the operator.', 'State delivery and collection boundaries before checkout.', 'Keep essential information lightweight and available without an elaborate animation.'], guide: 'mobile-first-design-importance' },
};
