import type { Metadata } from 'next';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { ArrowRight, Check, MapPin } from 'lucide-react';
import { Header } from '@/components/header';
import { Footer } from '@/components/footer';
import { JsonLd } from '@/components/json-ld';
import { getProvince, provinces } from '@/lib/locations';
import { services } from '@/lib/services';
import { absoluteUrl, pageMetadata, site } from '@/lib/site';

export function generateStaticParams(){return provinces.map(({slug})=>({slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const p=getProvince(slug);if(!p)return{};return pageMetadata({title:`Web Design in ${p.name}`,description:`Website design, ecommerce, SEO and web application development across ${p.name}, including ${p.towns.slice(0,4).join(', ')}.`,path:`/locations/${slug}`})}
export default async function ProvincePage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const p=getProvince(slug);if(!p)notFound();const schema={'@context':'https://schema.org','@graph':[{'@type':'Service',name:`Web design in ${p.name}`,serviceType:'Website design and development',provider:{'@id':`${site.url}/#organization`},areaServed:[{'@type':'AdministrativeArea',name:p.name},...p.towns.map(name=>({'@type':'City',name}))],url:absoluteUrl(`/locations/${slug}`)},{'@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Home',item:site.url},{'@type':'ListItem',position:2,name:'South Africa',item:absoluteUrl('/locations')},{'@type':'ListItem',position:3,name:p.name,item:absoluteUrl(`/locations/${slug}`)}]}]};return <><Header/><main id="main-content"><JsonLd id="location-schema" data={schema}/>
  <section className="page-hero"><div className="site-container page-hero-grid"><div><div className="breadcrumb"><Link href="/">Home</Link><span>/</span><Link href="/locations">South Africa</Link><span>/</span><span>{p.name}</span></div><p className="eyebrow"><MapPin size={14}/> {p.name}</p><h1>Web design in <em>{p.name}</em></h1></div><p className="lead">{p.lead}</p></div></section>
  <section className="content-section"><div className="site-container content-grid"><div><p className="eyebrow">The market</p><h2>Designed for how {p.name} businesses compete.</h2></div><div className="body-copy"><p>{p.opportunity}</p><div className="pill-list">{p.sectors.map(s=><span className="pill" key={s}>{s}</span>)}</div></div></div></section>
  <section className="content-section alt"><div className="site-container"><div className="section-heading-row"><div><p className="eyebrow">What we deliver</p><h2>From first search to qualified enquiry.</h2></div></div><div className="location-card-grid">{services.map((s)=><Link className="location-card" href={`/services/${s.slug}`} key={s.slug}><span>Service</span><h3>{s.shortName}</h3><p>{s.promise}</p><span className="card-link">Explore <ArrowRight size={15}/></span></Link>)}</div></div></section>
  <section className="content-section"><div className="site-container content-grid"><div><p className="eyebrow">Coverage directory</p><h2>Cities and towns across {p.name}.</h2><p style={{color:'var(--muted)',lineHeight:1.7}}>Our remote process is available across the province. A listed town is a service area, not a claimed physical office.</p></div><div className="town-directory">{p.towns.map(t=><span key={t}>{t}</span>)}</div></div></section>
  <section className="content-section dark"><div className="site-container content-grid"><div><p className="eyebrow eyebrow-light">Why the approach works</p><h2>Local relevance. National build quality.</h2></div><ul className="detail-list" style={{borderColor:'#393c43'}}>{['Mobile-first experiences for everyday South African devices','Fast pages designed to respect bandwidth and attention','South African payments, contact habits and commercial context','Clear regional relevance without copied city pages'].map(x=><li key={x} style={{borderColor:'#393c43'}}><Check size={18}/><strong>{x}</strong></li>)}</ul></div></section>
  <section className="content-section"><div className="site-container cta-panel"><h2>Planning a website in {p.name}?</h2><Link href="/contact" className="button button-light">Start with your goal <ArrowRight size={18}/></Link></div></section>
  </main><Footer/></>}
